const ENV = {
  BASE_URL: process.env.EXPO_BASE_URL,
  API_BASE_URL: process.env.EXPO_PUBLIC_API_BASE_URL,
  MAPBOX_ACCESS_TOKEN: process.env.EXPO_PUBLIC_MAPBOX_ACCESS_TOKEN,
  GOOGLE_MAPS_ANDROID_KEY: process.env.EXPO_PUBLIC_GOOGLE_MAPS_DEV_KEY,
};

export default ENV;
